# Generated by Django 6.1 on 2026-08-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niches_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('service', models.CharField(blank=True, choices=[('residential', 'Residential Interior Design'), ('commercial', 'Commercial Interior Design'), ('renovation', 'Renovation & Remodelling'), ('consultation', 'Design Consultation')], max_length=30)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
